CREATE TABLE IF NOT EXISTS T_DRAW_INFORMATION
(
    DRAW_ID                          INTEGER  PRIMARY KEY NOT NULL,
    YEAR_DRAW_NUMBER                 INT      not null,
    DRAW_DATE                        DATETIME not null,
    DRAW_DAY                         TEXT,
    FORCLUSION_DATE                  DATETIME,
    DRAW_NUMBER_IN_CYCLE             INT,
    CONSTRAINT T_DRAW_INFORMATION_YEAR_DRAW_NUMBER_uindex UNIQUE (YEAR_DRAW_NUMBER),
    CONSTRAINT FK_T_DRAW_INFORMATION_T_DRAW_ID FOREIGN KEY (DRAW_ID) REFERENCES T_DRAW (ID) ON DELETE CASCADE
);
