CREATE TABLE IF NOT EXISTS T_DRAW_ADDITIONAL_GAME
(
    DRAW_ID                               INTEGER PRIMARY KEY NOT NULL,
    JOKER_PLUS_NUMBER                     TEXT,
    MY_MILLION_NUMBER                     TEXT,
    EXCEPTIONAL_EURO_MILLIONS_DRAW_NUMBER TEXT,
    CONSTRAINT FK_T_DRAW_ADDITIONAL_GAME_T_DRAW_ID FOREIGN KEY (DRAW_ID) REFERENCES T_DRAW (ID) ON DELETE CASCADE
);
